###
#regsiter user
POST http://localhost:5000/api/auth/registerUser
Content-Type: application/json

{
    "username":"abbasgabol",
    "email":"abbasgabol321@gmail.com",
    "password":"password123"
}